/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as ProfitTrackerRouteImport } from './routes/profit-tracker'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as IrrigationTrackerRouteImport } from './routes/irrigation-tracker'
import { Route as ExpertCallRouteImport } from './routes/expert-call'
import { Route as DiseaseCheckRouteImport } from './routes/disease-check'
import { Route as CropRecommendRouteImport } from './routes/crop-recommend'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpertQueriesRouteImport } from './routes/expert.queries'
import { Route as ExpertDashboardRouteImport } from './routes/expert.dashboard'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitTrackerRoute = ProfitTrackerRouteImport.update({
  id: '/profit-tracker',
  path: '/profit-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const IrrigationTrackerRoute = IrrigationTrackerRouteImport.update({
  id: '/irrigation-tracker',
  path: '/irrigation-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertCallRoute = ExpertCallRouteImport.update({
  id: '/expert-call',
  path: '/expert-call',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseaseCheckRoute = DiseaseCheckRouteImport.update({
  id: '/disease-check',
  path: '/disease-check',
  getParentRoute: () => rootRouteImport,
} as any)
const CropRecommendRoute = CropRecommendRouteImport.update({
  id: '/crop-recommend',
  path: '/crop-recommend',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertQueriesRoute = ExpertQueriesRouteImport.update({
  id: '/expert/queries',
  path: '/expert/queries',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertDashboardRoute = ExpertDashboardRouteImport.update({
  id: '/expert/dashboard',
  path: '/expert/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/crop-recommend': typeof CropRecommendRoute
  '/disease-check': typeof DiseaseCheckRoute
  '/expert-call': typeof ExpertCallRoute
  '/irrigation-tracker': typeof IrrigationTrackerRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/profit-tracker': typeof ProfitTrackerRoute
  '/schemes': typeof SchemesRoute
  '/upgrade': typeof UpgradeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/expert/dashboard': typeof ExpertDashboardRoute
  '/expert/queries': typeof ExpertQueriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/crop-recommend': typeof CropRecommendRoute
  '/disease-check': typeof DiseaseCheckRoute
  '/expert-call': typeof ExpertCallRoute
  '/irrigation-tracker': typeof IrrigationTrackerRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/profit-tracker': typeof ProfitTrackerRoute
  '/schemes': typeof SchemesRoute
  '/upgrade': typeof UpgradeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/expert/dashboard': typeof ExpertDashboardRoute
  '/expert/queries': typeof ExpertQueriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/crop-recommend': typeof CropRecommendRoute
  '/disease-check': typeof DiseaseCheckRoute
  '/expert-call': typeof ExpertCallRoute
  '/irrigation-tracker': typeof IrrigationTrackerRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/profit-tracker': typeof ProfitTrackerRoute
  '/schemes': typeof SchemesRoute
  '/upgrade': typeof UpgradeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/users': typeof AdminUsersRoute
  '/expert/dashboard': typeof ExpertDashboardRoute
  '/expert/queries': typeof ExpertQueriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/chat'
    | '/community'
    | '/crop-recommend'
    | '/disease-check'
    | '/expert-call'
    | '/irrigation-tracker'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/profit-tracker'
    | '/schemes'
    | '/upgrade'
    | '/admin/dashboard'
    | '/admin/users'
    | '/expert/dashboard'
    | '/expert/queries'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/chat'
    | '/community'
    | '/crop-recommend'
    | '/disease-check'
    | '/expert-call'
    | '/irrigation-tracker'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/profit-tracker'
    | '/schemes'
    | '/upgrade'
    | '/admin/dashboard'
    | '/admin/users'
    | '/expert/dashboard'
    | '/expert/queries'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendar'
    | '/chat'
    | '/community'
    | '/crop-recommend'
    | '/disease-check'
    | '/expert-call'
    | '/irrigation-tracker'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/profit-tracker'
    | '/schemes'
    | '/upgrade'
    | '/admin/dashboard'
    | '/admin/users'
    | '/expert/dashboard'
    | '/expert/queries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  ChatRoute: typeof ChatRoute
  CommunityRoute: typeof CommunityRoute
  CropRecommendRoute: typeof CropRecommendRoute
  DiseaseCheckRoute: typeof DiseaseCheckRoute
  ExpertCallRoute: typeof ExpertCallRoute
  IrrigationTrackerRoute: typeof IrrigationTrackerRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ProfitTrackerRoute: typeof ProfitTrackerRoute
  SchemesRoute: typeof SchemesRoute
  UpgradeRoute: typeof UpgradeRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ExpertDashboardRoute: typeof ExpertDashboardRoute
  ExpertQueriesRoute: typeof ExpertQueriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit-tracker': {
      id: '/profit-tracker'
      path: '/profit-tracker'
      fullPath: '/profit-tracker'
      preLoaderRoute: typeof ProfitTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/irrigation-tracker': {
      id: '/irrigation-tracker'
      path: '/irrigation-tracker'
      fullPath: '/irrigation-tracker'
      preLoaderRoute: typeof IrrigationTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert-call': {
      id: '/expert-call'
      path: '/expert-call'
      fullPath: '/expert-call'
      preLoaderRoute: typeof ExpertCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disease-check': {
      id: '/disease-check'
      path: '/disease-check'
      fullPath: '/disease-check'
      preLoaderRoute: typeof DiseaseCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-recommend': {
      id: '/crop-recommend'
      path: '/crop-recommend'
      fullPath: '/crop-recommend'
      preLoaderRoute: typeof CropRecommendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert/queries': {
      id: '/expert/queries'
      path: '/expert/queries'
      fullPath: '/expert/queries'
      preLoaderRoute: typeof ExpertQueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expert/dashboard': {
      id: '/expert/dashboard'
      path: '/expert/dashboard'
      fullPath: '/expert/dashboard'
      preLoaderRoute: typeof ExpertDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  ChatRoute: ChatRoute,
  CommunityRoute: CommunityRoute,
  CropRecommendRoute: CropRecommendRoute,
  DiseaseCheckRoute: DiseaseCheckRoute,
  ExpertCallRoute: ExpertCallRoute,
  IrrigationTrackerRoute: IrrigationTrackerRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ProfitTrackerRoute: ProfitTrackerRoute,
  SchemesRoute: SchemesRoute,
  UpgradeRoute: UpgradeRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminUsersRoute: AdminUsersRoute,
  ExpertDashboardRoute: ExpertDashboardRoute,
  ExpertQueriesRoute: ExpertQueriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
